# Snakefile (controls) for structural connectome and time series preprocessing, analysis (pyspi)
# Usage: comment in/out processes as needed to execute pipeline components

import os
import pandas as pd

configfile: "config/config_controls.yml"

wildcard_constraints:
    subject = r"sub-[0-9a-fA-F]{12}|sub-C[0-9]{3}",
    run = r"01|02", 
    dir = r"RL|LR|AP|PA"

# load control list 
subjects = pd.read_excel(config["participants"], sheet_name="controls")
subjects = subjects["bids"]

# specify rule files
include: "rules/preprocess_timeseries_controls.smk"
include: "rules/connectome_controls.smk"
include: "rules/pyspi_controls.smk"

# handle acquisition parameters
def get_valid_inputs(pattern):
    """Find existing files that match the pattern"""
    valid_files = []
    for subject in subjects:
        for run in ["01"]:
            for dir in ["AP", "PA", "LR", "RL"]:
                # Check if the fMRIprep output exists
                bold_file = f"{config['fmriprep_dir']}/{subject}/func/{subject}_task-rest_dir-{dir}_run-{run}_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz"
                confounds_file = f"{config['fmriprep_dir']}/{subject}/func/{subject}_task-rest_dir-{dir}_run-{run}_desc-confounds_timeseries.tsv"
                
                if os.path.exists(bold_file) and os.path.exists(confounds_file):
                    valid_files.append(pattern.format(subject=subject, run=run, dir=dir))
    return valid_files

rule all: # preprocess_timeseries_controls.smk
    input: 
        expand("logs/{subject}/{subject}_vep_atlas_conversion.done", subject=subjects),
        get_valid_inputs("logs/{subject}/{subject}_task-rest_dir-{dir}_run-{run}_vep_atlas_resample.done"),
        get_valid_inputs("logs/{subject}/{subject}_task-rest_dir-{dir}_run-{run}_atlas_alignment_bold.done"),
        get_valid_inputs("logs/{subject}/{subject}_task-rest_dir-{dir}_run-{run}_preproc_bold_vep_timeseries.done")

# ============== OUT OF PIPE: run bash resources/rename_files.sh =========================================================================================================================

rule all: # connectome_controls.smk 
    input:
        expand("logs/{subject}/{subject}_vep_atlas_conversion.done", subject=subjects),
        expand("logs/{subject}/{subject}_transform_atlas.done", subject=subjects), 
        expand("logs/{subject}/{subject}_check_atlas_alignment_diff.done", subject=subjects),
        expand("logs/{subject}/{subject}_compute_connectome_N.done", subject=subjects),
        expand("logs/{subject}/{subject}_compute_connectome_L.done", subject=subjects)

rule all: # pyspi_controls.smk
    input:
        expand("logs/{subject}/{subject}_run-{run}_compute_spis.done", subject=subjects, run=["01", "02"])